name: Build Latest Distribution

on:
  push:
    branches:
      - release

permissions:
  contents: write

jobs:
  build-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Make Gradle executable
        run: chmod +x gradlew

      - name: Build distribution zip
        run: ./gradlew :app:fullDistZip --no-daemon

      - name: Upload artifact (for debugging)
        uses: actions/upload-artifact@v4
        with:
          name: dist-zip
          path: app/build/distributions/nand2tetris-CIS351.zip
      - name: Publish zip to latest-dist branch
        if: github.ref == 'refs/heads/release'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git fetch origin
          git checkout -B latest-dist
          mkdir -p dist
          cp app/build/distributions/nand2tetris-CIS351.zip dist/
          git add dist/nand2tetris-CIS351.zip
          git commit -m "Update latest distribution ($(date -u +%Y-%m-%dT%H:%M:%SZ))" || echo "No changes"
          git push origin latest-dist --force
