name: Build Latest Distribution

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Make Gradle executable
        run: chmod +x gradlew

      - name: Build distribution zip
        run: ./gradlew :app:fullDistZip --no-daemon

      - name: Upload artifact (for debugging)
        uses: actions/upload-artifact@v4
        with:
          name: dist-zip
          path: app/build/distributions/nand2tetris-CIS351.zip
